Feature/obj 492 extensions cookie consent
companieshouse/extensions-web pull request #97
Opened 2021-03-18 15:04 UTC by mattch1

Cookie consent for extensions

2021-03-18 15:32 UTC, SVarallo approved these changes

2021-03-23 16:59 UTC, SVarallo requested changes

2021-03-23 16:59 UTC, SVarallo commented on views/includes/piwik-scripts.html
> +  window.SERVICE_NAME = 'extensions'
How come this has changed from 'extend-filing-deadline' in the original?

2021-03-24 10:27 UTC, mattch1 commented
Work completed on another branch.

2021-03-24 10:27 UTC, closed without merging